export const AUEYUSERNAME = "MaewmeawRokjit123"
export const AUEYDISPLAYNAME = "น้องเอยขี้เซาโรคจิต"
export const AUEYCOLORTHEME = "#ff85c0"
export const TESTUSERNAME = "test_user"
export const TESTDISPLAYNAME = "TEST"
export const TESTCOLORTHEME = "#8c8c8c"
export const SPYUSERNAME = "HandsomeWolf"
export const SPYDISPLAYNAME = "พี่ปายหมาปาสุดหล่อ"
export const SPYCOLORTHEME = "#1677ff"

