name: CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with: 
          context: ./haus64_web_frontend
          build-args: |
            "NEXT_PUBLIC_BACKEND_API=${{ secrets.NEXT_PUBLIC_BACKEND_API }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auengauey-diary-frontend:latest

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop web-frontend || true
            docker rm web-frontend || true
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/auengauey-diary-frontend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/auengauey-diary-frontend:latest
            docker run -d -p 3000:3000 \
              --name web-frontend \
              ${{ secrets.DOCKERHUB_USERNAME }}/auengauey-diary-frontend:latest

